// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartySaver.Data;

#nullable disable

namespace PartySaver.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240918183810_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PartySaver.Data.Models.CdnFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("PartySaver.Data.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PhotoFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviewFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhotoFileId");

                    b.HasIndex("PreviewFileId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PartySaver.Data.Models.Photo", b =>
                {
                    b.HasOne("PartySaver.Data.Models.CdnFile", "PhotoFile")
                        .WithMany()
                        .HasForeignKey("PhotoFileId");

                    b.HasOne("PartySaver.Data.Models.CdnFile", "PreviewFile")
                        .WithMany()
                        .HasForeignKey("PreviewFileId");

                    b.Navigation("PhotoFile");

                    b.Navigation("PreviewFile");
                });
#pragma warning restore 612, 618
        }
    }
}
